from pydantic import BaseModel, Field
from typing import Optional 
from datetime import datetime

from models.trip.trip_enums import CancellationSubStatusEnum

class CancelationPolicySchema(BaseModel):
    trip_type_id: str = Field(..., description="ID of the trip type")
    region_id: Optional[str] = Field(None, description="ID of the region for which this cancelation policy applies")
    state_id: Optional[str] = Field(None, description="ID of the state for which this cancelation policy applies")
    free_cutoff_minutes: int = Field(..., description="Free cancellation cutoff in minutes")
    free_cutoff_time_label: Optional[str] = Field(None, description="Label for free cutoff time, e.g., '30 minutes before'")
    refund_percentage: float = Field(..., description="Percentage of the fare to be refunded against advance payment. 100% refund if cancellation is made from our end or by customer on or before the free cutoff time. Partial refund if cancellation is made after the free cutoff time. For example, 100.0 for full refund, 50.0 for half refund, 0.0 for no refund.")
    
    effective_from: Optional[datetime] = Field(None, description="DateTime from which this policy is effective")
    effective_to: Optional[datetime] = Field(None, description="DateTime until which this policy is effective")
    is_active: bool = Field(True, description="Indicates if the cancelation policy is active")

    class Config:
        from_attributes = True

class CancelationSchema(BaseModel):
    id: Optional[str] = Field(None, description="ID of the cancellation record, generated by the system")
    entity_id: Optional[str] = Field(None, description="ID of the trip being canceled")
    canceled_by: Optional[str] = Field(None, description="User ID of the person who canceled the trip or 'system' if canceled by the system")
    cancellation_sub_status: Optional[CancellationSubStatusEnum] = Field(CancellationSubStatusEnum.none, description="Sub-status for cancellation, e.g., 'no_show', 'late_cancellation', etc.")
    reason: Optional[str] = Field(None, description="Reason for cancellation provided by the customer or system user/admin")
    created_at: Optional[datetime] = Field(None, description="Date and time when the cancellation record was created")
    updated_at: Optional[datetime] = Field(None, description="Date and time when the cancellation record was updated")
    
    class Config:
        from_attributes = True
        extra = "allow"
 