version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cabbo-backend-dev
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
      - ./share:/app/share
    restart: always

  db:
    image: mysql:8
    container_name: cabbo-db-dev
    restart: always
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: