"""db_changes_27022026

Revision ID: 02c82e459735
Revises: bed92b8bfa47
Create Date: 2026-02-27 02:08:48.993330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02c82e459735'
down_revision: Union[str, Sequence[str], None] = 'bed92b8bfa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_earnings', sa.Column('extra_earnings', sa.Float(), nullable=True))
    op.add_column('driver_earnings', sa.Column('extra_earnings_breakdown', sa.JSON(), nullable=True))
    op.add_column('driver_earnings', sa.Column('total_earnings', sa.Float(), nullable=False))
    op.alter_column('driver_earnings', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.create_index(op.f('ix_driver_earnings_created_by'), 'driver_earnings', ['created_by'], unique=False)
    op.add_column('driver_ratings', sa.Column('last_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('driver_ratings', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.create_index(op.f('ix_driver_ratings_created_by'), 'driver_ratings', ['created_by'], unique=False)
    op.alter_column('drivers', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.create_index(op.f('ix_drivers_created_by'), 'drivers', ['created_by'], unique=False)
    op.add_column('trips', sa.Column('refund_payment', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('refund_payment_reason', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('extra_payment_to_driver', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'trips', 'customers', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'extra_payment_to_driver')
    op.drop_column('trips', 'refund_payment_reason')
    op.drop_column('trips', 'refund_payment')
    op.drop_index(op.f('ix_drivers_created_by'), table_name='drivers')
    op.alter_column('drivers', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               comment=None,
               existing_comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.drop_index(op.f('ix_driver_ratings_created_by'), table_name='driver_ratings')
    op.alter_column('driver_ratings', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               comment=None,
               existing_comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.drop_column('driver_ratings', 'last_modified')
    op.drop_index(op.f('ix_driver_earnings_created_by'), table_name='driver_earnings')
    op.alter_column('driver_earnings', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               comment=None,
               existing_comment='ID of the user or system that created this record',
               existing_nullable=False)
    op.drop_column('driver_earnings', 'total_earnings')
    op.drop_column('driver_earnings', 'extra_earnings_breakdown')
    op.drop_column('driver_earnings', 'extra_earnings')
    # ### end Alembic commands ###
