"""rename-col-in-refund-model

Revision ID: 0517f1353c1e
Revises: c0adf98e05af
Create Date: 2026-03-22 16:57:18.947525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0517f1353c1e'
down_revision: Union[str, Sequence[str], None] = 'c0adf98e05af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('refund_description', sa.String(length=255), nullable=False))
    op.drop_column('refunds', 'refund_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('refund_reason', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('refunds', 'refund_description')
    # ### end Alembic commands ###
