"""customer_session

Revision ID: 05833d2c73e4
Revises: b6a1f7c2d9e4
Create Date: 2026-08-05 07:34:07.632140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05833d2c73e4'
down_revision: Union[str, Sequence[str], None] = 'b6a1f7c2d9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_sessions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_customer_sessions_customer_id'), 'customer_sessions', ['customer_id'], unique=False)
    op.create_index('ix_customer_sessions_customer_id_is_active', 'customer_sessions', ['customer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_customer_sessions_expires_at'), 'customer_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_customer_sessions_token_hash'), 'customer_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_sessions_token_hash'), table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_expires_at'), table_name='customer_sessions')
    op.drop_index('ix_customer_sessions_customer_id_is_active', table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_customer_id'), table_name='customer_sessions')
    op.drop_table('customer_sessions')
    # ### end Alembic commands ###
