"""add-hop-limit

Revision ID: 08866df2da19
Revises: 2985648f68f2
Create Date: 2026-04-18 16:43:04.807763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08866df2da19'
down_revision: Union[str, Sequence[str], None] = '2985648f68f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripwise_pricing_config', sa.Column('max_hops_allowed', sa.Integer(), nullable=True, comment='Max hops/stops allowed for outstation trips'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'max_hops_allowed')
    # ### end Alembic commands ###
