"""changes-5-14

Revision ID: 0e290c77721d
Revises: f53323a876af
Create Date: 2026-05-14 02:28:46.915789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e290c77721d'
down_revision: Union[str, Sequence[str], None] = 'f53323a876af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripwise_pricing_config', sa.Column('min_outbound_distance_km', sa.Float(), nullable=True))
    op.add_column('tripwise_pricing_config', sa.Column('min_days_allowed', sa.Integer(), nullable=True, comment='Min days allowed for outstation trips'))
    op.drop_column('tripwise_pricing_config', 'min_distance_km')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripwise_pricing_config', sa.Column('min_distance_km', mysql.FLOAT(), nullable=True))
    op.drop_column('tripwise_pricing_config', 'min_days_allowed')
    op.drop_column('tripwise_pricing_config', 'min_outbound_distance_km')
    # ### end Alembic commands ###
