"""db-changes-05-03

Revision ID: 0f8292e8a572
Revises: f70c490b8b1f
Create Date: 2026-03-05 02:01:59.256490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f8292e8a572'
down_revision: Union[str, Sequence[str], None] = 'f70c490b8b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('refund_status', sa.String(length=50), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_reason', sa.String(length=255), nullable=False),
    sa.Column('refund_details', sa.JSON(), nullable=True),
    sa.Column('refund_initiated_datetime', sa.DateTime(), nullable=True),
    sa.Column('refund_type', sa.String(length=50), nullable=True),
    sa.Column('refund_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_entity_id'), 'refunds', ['entity_id'], unique=False)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=True)
    op.add_column('trips', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'trips', 'refunds', ['refund_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trips', 'extra_payment_to_driver')
    op.drop_column('trips', 'refund_payment')
    op.drop_column('trips', 'refund_status')
    op.drop_column('trips', 'refund_details')
    op.drop_column('trips', 'refund_type')
    op.drop_column('trips', 'refund_payment_reason')
    op.drop_column('trips', 'refund_initiated_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('refund_initiated_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('trips', sa.Column('refund_payment_reason', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('trips', sa.Column('refund_type', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('trips', sa.Column('refund_details', mysql.JSON(), nullable=True))
    op.add_column('trips', sa.Column('refund_status', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('trips', sa.Column('refund_payment', mysql.FLOAT(), nullable=True))
    op.add_column('trips', sa.Column('extra_payment_to_driver', mysql.JSON(), nullable=True))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_column('trips', 'is_active')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_entity_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
