"""remove-redndant-driver-rating-cols

Revision ID: 1f428598eb8c
Revises: ac9e82e74c3c
Create Date: 2026-03-26 02:34:11.550883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f428598eb8c'
down_revision: Union[str, Sequence[str], None] = 'ac9e82e74c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_ratings_created_by'), table_name='driver_ratings')
    op.drop_column('driver_ratings', 'last_modified')
    op.drop_column('driver_ratings', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_ratings', sa.Column('created_by', mysql.CHAR(length=36), nullable=False, comment='ID of the user or system that created this record'))
    op.add_column('driver_ratings', sa.Column('last_modified', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.create_index(op.f('ix_driver_ratings_created_by'), 'driver_ratings', ['created_by'], unique=False)
    # ### end Alembic commands ###
