"""dbchange245

Revision ID: 2149c5ba52d4
Revises: cd6868c5838f
Create Date: 2026-05-24 17:20:54.537987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2149c5ba52d4'
down_revision: Union[str, Sequence[str], None] = 'cd6868c5838f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_package_config', sa.Column('best_intended_for', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_package_config', 'best_intended_for')
    # ### end Alembic commands ###
