"""adjust-max-days-allowed-for-outstation-trips

Revision ID: 2985648f68f2
Revises: cada1a621bf5
Create Date: 2026-04-18 16:18:43.246944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2985648f68f2'
down_revision: Union[str, Sequence[str], None] = 'cada1a621bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outstation_cab_pricing', 'max_days_allowed')
    op.add_column('tripwise_pricing_config', sa.Column('max_days_allowed', sa.Integer(), nullable=True, comment='Max days allowed for outstation trips'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'max_days_allowed')
    op.add_column('outstation_cab_pricing', sa.Column('max_days_allowed', mysql.INTEGER(), autoincrement=False, nullable=False, comment='Max 7 days allowed for outstation trips'))
    # ### end Alembic commands ###
