"""initdb255

Revision ID: 2a1bff2eeea2
Revises: 2149c5ba52d4
Create Date: 2026-05-25 00:53:59.181915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1bff2eeea2'
down_revision: Union[str, Sequence[str], None] = '2149c5ba52d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_trips', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('temp_trips', sa.Column('utc_offset', sa.Integer(), nullable=True))
    op.add_column('trips', sa.Column('timezone', sa.String(length=64), nullable=True))
    op.add_column('trips', sa.Column('utc_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'utc_offset')
    op.drop_column('trips', 'timezone')
    op.drop_column('temp_trips', 'utc_offset')
    op.drop_column('temp_trips', 'timezone')
    # ### end Alembic commands ###
