"""remove_effective_from_to_in_cancelation_policy_tbl__27022026

Revision ID: 2aa106540745
Revises: 41391082c950
Create Date: 2026-02-27 02:26:28.676840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2aa106540745'
down_revision: Union[str, Sequence[str], None] = '41391082c950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancellation_policies', 'effective_from')
    op.drop_column('cancellation_policies', 'effective_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation_policies', sa.Column('effective_to', mysql.DATETIME(), nullable=True))
    op.add_column('cancellation_policies', sa.Column('effective_from', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
