"""add_booking_id_as_idx

Revision ID: 2d1bd7e5df0b
Revises: fb19df47744b
Create Date: 2026-02-02 02:50:01.748583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1bd7e5df0b'
down_revision: Union[str, Sequence[str], None] = 'fb19df47744b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_booking_id'), table_name='trips')
    op.create_index(op.f('ix_trips_booking_id'), 'trips', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_booking_id'), table_name='trips')
    op.create_index(op.f('ix_trips_booking_id'), 'trips', ['booking_id'], unique=False)
    # ### end Alembic commands ###
