"""user_sessions

Revision ID: 2dfa604c3954
Revises: 05833d2c73e4
Create Date: 2026-08-08 00:05:43.934991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2dfa604c3954'
down_revision: Union[str, Sequence[str], None] = '05833d2c73e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_user_sessions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_sys_user_sessions_user_id_is_active', 'system_user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_system_user_sessions_expires_at'), 'system_user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_system_user_sessions_token_hash'), 'system_user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_system_user_sessions_user_id'), 'system_user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_user_sessions_user_id'), table_name='system_user_sessions')
    op.drop_index(op.f('ix_system_user_sessions_token_hash'), table_name='system_user_sessions')
    op.drop_index(op.f('ix_system_user_sessions_expires_at'), table_name='system_user_sessions')
    op.drop_index('ix_sys_user_sessions_user_id_is_active', table_name='system_user_sessions')
    op.drop_table('system_user_sessions')
    # ### end Alembic commands ###
