"""customer-support

Revision ID: 32fabef9e8e2
Revises: 
Create Date: 2026-06-28 01:05:49.150538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '32fabef9e8e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_contacts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('support_type', sa.Enum('customer', 'driver', 'booking', 'payment', 'emergency', 'general', name='customer_support_type_enum'), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_contacts_email'), 'support_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_support_contacts_id'), 'support_contacts', ['id'], unique=True)
    op.create_index(op.f('ix_support_contacts_is_active'), 'support_contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_contacts_phone_number'), 'support_contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_support_contacts_support_type'), 'support_contacts', ['support_type'], unique=False)
    op.create_table('support_routing_rules',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('support_contact_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('scope_type', sa.Enum('country', 'state', 'region', name='support_scope_enum'), nullable=False),
    sa.Column('scope_id', mysql.CHAR(length=36), nullable=False, comment='ID of the country, state, or region selected by scope_type.'),
    sa.Column('country_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('trip_type_scope', mysql.CHAR(length=36), nullable=False, comment="Use 'all' or a TripTypeEnum value such as local/outstation."),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Lower values win when multiple active support rules match.'),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("((scope_type = 'country' AND country_id = scope_id AND state_id IS NULL AND region_id IS NULL) OR (scope_type = 'state' AND state_id = scope_id AND country_id IS NULL AND region_id IS NULL) OR (scope_type = 'region' AND region_id = scope_id AND country_id IS NULL AND state_id IS NULL))", name='ck_support_rule_scope_matches_geography'),
    sa.ForeignKeyConstraint(['country_id'], ['countries_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_contact_id'], ['support_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('support_contact_id', 'scope_type', 'scope_id', 'trip_type_scope', name='uq_support_contact_scope_trip_type')
    )
    op.create_index(op.f('ix_support_routing_rules_country_id'), 'support_routing_rules', ['country_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_id'), 'support_routing_rules', ['id'], unique=True)
    op.create_index(op.f('ix_support_routing_rules_is_active'), 'support_routing_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_region_id'), 'support_routing_rules', ['region_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_scope_id'), 'support_routing_rules', ['scope_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_scope_type'), 'support_routing_rules', ['scope_type'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_state_id'), 'support_routing_rules', ['state_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_support_contact_id'), 'support_routing_rules', ['support_contact_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_trip_type_scope'), 'support_routing_rules', ['trip_type_scope'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_routing_rules_trip_type_scope'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_support_contact_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_state_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_scope_type'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_scope_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_region_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_is_active'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_country_id'), table_name='support_routing_rules')
    op.drop_table('support_routing_rules')
    op.drop_index(op.f('ix_support_contacts_support_type'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_phone_number'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_is_active'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_id'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_email'), table_name='support_contacts')
    op.drop_table('support_contacts')
    # ### end Alembic commands ###
