"""changes-on0904

Revision ID: 33f810b4d171
Revises: f76defb20f8c
Create Date: 2026-04-09 01:04:07.857693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33f810b4d171'
down_revision: Union[str, Sequence[str], None] = 'f76defb20f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.ENUM('processed', 'pending', 'completed', 'failed', 'unknown', 'initiated'),
               type_=sa.Enum('initiated', 'processed', 'pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               existing_comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    op.add_column('tripwise_pricing_config', sa.Column('min_platform_fee', sa.Float(), nullable=True, comment='Minimum platform fee charged to customer for this trip type in this region or state, regardless of total fare. This helps ensure that we cover our costs for low-fare trips.'))
    op.add_column('tripwise_pricing_config', sa.Column('max_platform_fee', sa.Float(), nullable=True, comment='Maximum platform fee charged to customer for this trip type in this region or state, regardless of total fare. This helps ensure that we do not overcharge for high-fare trips.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'max_platform_fee')
    op.drop_column('tripwise_pricing_config', 'min_platform_fee')
    op.alter_column('refunds', 'refund_status',
               existing_type=sa.Enum('initiated', 'processed', 'pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               type_=mysql.ENUM('processed', 'pending', 'completed', 'failed', 'unknown', 'initiated'),
               existing_comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    # ### end Alembic commands ###
