"""driver-rating-is-flagged-column-add

Revision ID: 3db86ccddd92
Revises: 1f428598eb8c
Create Date: 2026-03-27 01:49:01.511777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db86ccddd92'
down_revision: Union[str, Sequence[str], None] = '1f428598eb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_ratings', sa.Column('is_flagged', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_ratings', 'is_flagged')
    # ### end Alembic commands ###
