"""make trip_id unique in driver earning

Revision ID: 3f692369fdd8
Revises: e812eb0dfff3
Create Date: 2026-04-04 01:30:47.075324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f692369fdd8'
down_revision: Union[str, Sequence[str], None] = 'e812eb0dfff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'driver_earnings', ['trip_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_earnings', type_='unique')
    # ### end Alembic commands ###
