"""change_data_type_for_created_by__in_cancelation_policy_tbl__27022026

Revision ID: 41391082c950
Revises: ccbd163ed9e0
Create Date: 2026-02-27 02:24:56.161387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41391082c950'
down_revision: Union[str, Sequence[str], None] = 'ccbd163ed9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cancellation_policies', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cancellation_policies', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    # ### end Alembic commands ###
