"""Add composite unique constraints to pricing tables

Revision ID: 500b3a557f0d
Revises: ee73ec77114d
Create Date: 2026-02-10 00:32:21.055703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '500b3a557f0d'
down_revision: Union[str, Sequence[str], None] = 'ee73ec77114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cab_types_master', 'cab_names',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('cab_types_master', 'inventory_cab_names',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_unique_constraint('uq_cab_fuel_state', 'permit_fee_config', ['cab_type_id', 'fuel_type_id', 'state_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cab_fuel_state', 'permit_fee_config', type_='unique')
    op.alter_column('cab_types_master', 'inventory_cab_names',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('cab_types_master', 'cab_names',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
