"""db-changes-31726

Revision ID: 547fd8fa623c
Revises: 892240022003
Create Date: 2026-03-17 16:27:07.593784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '547fd8fa623c'
down_revision: Union[str, Sequence[str], None] = '892240022003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('policy_id', sa.String(length=255), nullable=True))
    op.alter_column('refunds', 'refund_provider',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('razorpay', 'stripe', 'phonepe', name='paymentprovider'),
               comment='Payment provider used for processing the refund, e.g., Stripe, PayPal, etc.',
               existing_nullable=True)
    op.create_index(op.f('ix_refunds_policy_id'), 'refunds', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_policy_id'), table_name='refunds')
    op.alter_column('refunds', 'refund_provider',
               existing_type=sa.Enum('razorpay', 'stripe', 'phonepe', name='paymentprovider'),
               type_=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='Payment provider used for processing the refund, e.g., Stripe, PayPal, etc.',
               existing_nullable=True)
    op.drop_column('refunds', 'policy_id')
    # ### end Alembic commands ###
