"""remove_bearer_token_last_seen

Revision ID: 5597f976342f
Revises: 2dfa604c3954
Create Date: 2026-08-08 00:48:56.052103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5597f976342f'
down_revision: Union[str, Sequence[str], None] = '2dfa604c3954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_seen')
    op.drop_column('customers', 'bearer_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bearer_token', mysql.TEXT(), nullable=True))
    op.add_column('customers', sa.Column('last_seen', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
