"""db-changes-41926-3

Revision ID: 56a2c591a5f9
Revises: d2d984f231a8
Create Date: 2026-04-19 18:15:42.533460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a2c591a5f9'
down_revision: Union[str, Sequence[str], None] = 'd2d984f231a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airports_master', sa.Column('provider', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airports_master', 'provider')
    # ### end Alembic commands ###
