"""change-created-at-updated-to-utc-refund-orm

Revision ID: 5da210a210be
Revises: 4c827be6fb71
Create Date: 2026-03-22 19:03:46.738182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da210a210be'
down_revision: Union[str, Sequence[str], None] = '4c827be6fb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
