"""db-changes-01032026

Revision ID: 62842d366e66
Revises: 2aa106540745
Create Date: 2026-03-01 00:46:28.886485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62842d366e66'
down_revision: Union[str, Sequence[str], None] = '2aa106540745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries_master', sa.Column('currency_decimal_places', sa.Integer(), nullable=False))
    op.add_column('countries_master', sa.Column('currency_in_words', sa.String(length=32), nullable=False))
    op.add_column('countries_master', sa.Column('currency_international_name', sa.String(length=32), nullable=False))
    op.add_column('countries_master', sa.Column('currency_symbol_position', sa.String(length=8), nullable=False))
    op.add_column('countries_master', sa.Column('currency_code_position', sa.String(length=8), nullable=False))
    op.add_column('countries_master', sa.Column('currency_thousand_separator', sa.String(length=8), nullable=False))
    op.add_column('countries_master', sa.Column('currency_decimal_separator', sa.String(length=8), nullable=False))
    op.add_column('countries_master', sa.Column('currency_lowest_unit_name', sa.String(length=32), nullable=False))
    op.add_column('countries_master', sa.Column('currency_lowest_unit_conversion_factor', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'countries_master', ['currency_international_name'])
    op.create_unique_constraint(None, 'countries_master', ['currency_in_words'])
    op.create_unique_constraint(None, 'countries_master', ['currency_lowest_unit_name'])
    op.add_column('trips', sa.Column('cancelation_datetime', sa.DateTime(), nullable=True))
    op.add_column('trips', sa.Column('refund_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'refund_details')
    op.drop_column('trips', 'cancelation_datetime')
    op.drop_constraint(None, 'countries_master', type_='unique')
    op.drop_constraint(None, 'countries_master', type_='unique')
    op.drop_constraint(None, 'countries_master', type_='unique')
    op.drop_column('countries_master', 'currency_lowest_unit_conversion_factor')
    op.drop_column('countries_master', 'currency_lowest_unit_name')
    op.drop_column('countries_master', 'currency_decimal_separator')
    op.drop_column('countries_master', 'currency_thousand_separator')
    op.drop_column('countries_master', 'currency_code_position')
    op.drop_column('countries_master', 'currency_symbol_position')
    op.drop_column('countries_master', 'currency_international_name')
    op.drop_column('countries_master', 'currency_in_words')
    op.drop_column('countries_master', 'currency_decimal_places')
    # ### end Alembic commands ###
