"""db-changes-03-06-02

Revision ID: 6321b97dd0eb
Revises: 6b055843e244
Create Date: 2026-03-06 02:10:26.276530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6321b97dd0eb'
down_revision: Union[str, Sequence[str], None] = '6b055843e244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disputes', 'dispute_type',
               existing_type=mysql.ENUM('fare', 'service', 'other','unknown'),
               comment='Type of dispute, e.g., fare, service, etc.',
               default=sa.text("'unknown'"),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disputes', 'dispute_type',
               existing_type=mysql.ENUM('fare', 'service', 'other'),
               comment=None,
               existing_comment='Type of dispute, e.g., fare, service, etc.',
               existing_nullable=False)
    # ### end Alembic commands ###
