"""db-changes-03-06-03

Revision ID: 6c579ba70ec0
Revises: 6321b97dd0eb
Create Date: 2026-03-06 02:41:54.556969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c579ba70ec0'
down_revision: Union[str, Sequence[str], None] = '6321b97dd0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'disputes', ['entity_id'])
    op.create_unique_constraint('uq_driver_trip_earning', 'driver_earnings', ['driver_id', 'trip_id'])
    op.drop_index(op.f('ix_refunds_entity_id'), table_name='refunds')
    op.create_index(op.f('ix_refunds_entity_id'), 'refunds', ['entity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_entity_id'), table_name='refunds')
    op.create_index(op.f('ix_refunds_entity_id'), 'refunds', ['entity_id'], unique=False)
    op.drop_constraint('uq_driver_trip_earning', 'driver_earnings', type_='unique')
    op.drop_constraint(None, 'disputes', type_='unique')
    # ### end Alembic commands ###
