"""rate-per-min-per-km

Revision ID: 716554f8ba12
Revises: 2a1bff2eeea2
Create Date: 2026-06-03 01:26:01.385854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716554f8ba12'
down_revision: Union[str, Sequence[str], None] = '2a1bff2eeea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_trips', sa.Column('rate_per_min', sa.Float(), nullable=True, comment='Applicable for hourly rental trips, this is the rate per minute for the trip which is used to calculate the final price for hourly rental trips based on the total duration of the trip. This field is populated based on the package chosen by the customer and the region-specific pricing configured in the system for that package and trip type.'))
    op.add_column('temp_trips', sa.Column('rate_per_km', sa.Float(), nullable=True, comment='Applicable for outstation trips, airport transfers, and hourly rental trips, this is the rate per km for the trip which is used to calculate the final price based on the total distance of the trip. This field is populated based on the package chosen by the customer and the region/state-specific pricing configured in the system for that package and trip type.'))
    op.add_column('trips', sa.Column('rate_per_min', sa.Float(), nullable=True, comment='Applicable for hourly rental trips, this is the rate per minute for the trip which is used to calculate the final price for hourly rental trips based on the total duration of the trip. This field is populated based on the package chosen by the customer and the region-specific pricing configured in the system for that package and trip type.'))
    op.add_column('trips', sa.Column('rate_per_km', sa.Float(), nullable=True, comment='Applicable for outstation trips, airport transfers, and hourly rental trips, this is the rate per km for the trip which is used to calculate the final price based on the total distance of the trip. This field is populated based on the package chosen by the customer and the region/state-specific pricing configured in the system for that package and trip type.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'rate_per_km')
    op.drop_column('trips', 'rate_per_min')
    op.drop_column('temp_trips', 'rate_per_km')
    op.drop_column('temp_trips', 'rate_per_min')
    # ### end Alembic commands ###
