"""change-cab-type-orm

Revision ID: 71d859cb2452
Revises: 716554f8ba12
Create Date: 2026-06-23 12:23:02.912125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d859cb2452'
down_revision: Union[str, Sequence[str], None] = '716554f8ba12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_types_master', sa.Column('passenger_capacity', sa.Integer(), nullable=True))
    op.add_column('cab_types_master', sa.Column('luggage_capacity', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab_types_master', 'luggage_capacity')
    op.drop_column('cab_types_master', 'passenger_capacity')
    # ### end Alembic commands ###
