"""db-changes-03-07

Revision ID: 75c32ee2b654
Revises: 6c579ba70ec0
Create Date: 2026-03-07 00:49:33.138283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '75c32ee2b654'
down_revision: Union[str, Sequence[str], None] = '6c579ba70ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    #op.add_column('driver_earnings', sa.Column('is_active', sa.Boolean(), nullable=False))
    # Drop FK constraints FIRST (before indexes in MySQL)
    op.drop_constraint('trips_ibfk_6', 'trips', type_='foreignkey')  # verify actual name
    op.drop_constraint('trips_ibfk_7', 'trips', type_='foreignkey')  # verify actual name
    # Then drop the unique indexes
    op.drop_index('refund_id', table_name='trips')
    op.drop_index('dispute_id', table_name='trips')
    # Finally drop the columns
    op.drop_column('trips', 'refund_id')
    op.drop_column('trips', 'dispute_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('dispute_id', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('trips', sa.Column('refund_id', mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(op.f('trips_ibfk_7'), 'trips', 'disputes', ['dispute_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('trips_ibfk_6'), 'trips', 'refunds', ['refund_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('refund_id'), 'trips', ['refund_id'], unique=True)
    op.create_index(op.f('dispute_id'), 'trips', ['dispute_id'], unique=True)
    op.drop_column('driver_earnings', 'is_active')
    # ### end Alembic commands ###
