"""add-included_kms_column_in_trips

Revision ID: 8522de7b932c
Revises: 7468d1b727cb
Create Date: 2026-02-02 02:38:04.063609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8522de7b932c'
down_revision: Union[str, Sequence[str], None] = '7468d1b727cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_trips', sa.Column('included_kms', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('included_kms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
