"""db-changes-03-08

Revision ID: 892240022003
Revises: 8c766cfe0e72
Create Date: 2026-03-08 01:15:32.204357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '892240022003'
down_revision: Union[str, Sequence[str], None] = '8c766cfe0e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_cancellations',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('canceled_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('cancellation_sub_status', sa.Enum('none', 'customer_cancelled', 'customer_no_show', 'driver_cancelled', 'driver_unavailable', 'driver_no_show', 'other', name='cancellation_sub_status_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_cancellations_entity_id'), 'trip_cancellations', ['entity_id'], unique=True)
    op.create_index(op.f('ix_trip_cancellations_id'), 'trip_cancellations', ['id'], unique=True)
    op.add_column('disputes', sa.Column('dispute_trigger', sa.Enum('manual', 'automatic', name='disputetriggerenum'), nullable=True, comment="Description of how the dispute was triggered, e.g., 'manual', 'automatic'"))
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed', 'unknown', 'processed'),
               type_=sa.Enum('processed', 'pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               existing_comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    op.drop_column('trip_status_audits', 'cancellation_sub_status')
    op.drop_column('trips', 'cancelation_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('cancelation_datetime', mysql.DATETIME(), nullable=True))
    op.add_column('trip_status_audits', sa.Column('cancellation_sub_status', mysql.ENUM('none', 'customer_cancelled', 'customer_no_show', 'super_admin_cancelled', 'driver_admin_cancelled', 'driver_cancelled', 'driver_unavailable', 'driver_no_show', 'finance_admin_cancelled', 'customer_preferences_not_met', 'other'), nullable=True, comment='Detailed cancellation reason for analytics (nullable, only for cancelled trips)'))
    op.alter_column('refunds', 'refund_status',
               existing_type=sa.Enum('processed', 'pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               type_=mysql.ENUM('pending', 'completed', 'failed', 'unknown', 'processed'),
               existing_comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    op.drop_column('disputes', 'dispute_trigger')
    op.drop_index(op.f('ix_trip_cancellations_id'), table_name='trip_cancellations')
    op.drop_index(op.f('ix_trip_cancellations_entity_id'), table_name='trip_cancellations')
    op.drop_table('trip_cancellations')
    # ### end Alembic commands ###
