"""add-refund-retried-datetime

Revision ID: 897f1a68e8ab
Revises: 5da210a210be
Create Date: 2026-03-22 19:07:31.061347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897f1a68e8ab'
down_revision: Union[str, Sequence[str], None] = '5da210a210be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refunds', sa.Column('refund_retried_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'refund_retried_datetime')
    # ### end Alembic commands ###
