"""db-column-changes-with-active-ind

Revision ID: 8bbd84f388b2
Revises: 
Create Date: 2026-02-04 00:36:21.078028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbd84f388b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_types_master', sa.Column('is_active', sa.Boolean(True), nullable=False))
    op.add_column('fuel_types_master', sa.Column('is_active', sa.Boolean(True), nullable=False))
    op.add_column('trip_types_master', sa.Column('is_active', sa.Boolean(True), nullable=False))
    op.drop_index(op.f('ix_trips_booking_id'), table_name='trips')
    op.create_index(op.f('ix_trips_booking_id'), 'trips', ['booking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_booking_id'), table_name='trips')
    op.create_index(op.f('ix_trips_booking_id'), 'trips', ['booking_id'], unique=False)
    op.drop_column('trip_types_master', 'is_active')
    op.drop_column('fuel_types_master', 'is_active')
    op.drop_column('cab_types_master', 'is_active')
    # ### end Alembic commands ###
