"""db-changes-03-07-v2

Revision ID: 8c766cfe0e72
Revises: 75c32ee2b654
Create Date: 2026-03-07 02:24:39.601370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c766cfe0e72'
down_revision: Union[str, Sequence[str], None] = '75c32ee2b654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed', 'unknown', 'processed'),
               comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.ENUM('pending', 'completed', 'failed', 'unknown'),
               comment=None,
               existing_comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.',
               existing_nullable=True)
    # ### end Alembic commands ###
