"""roof_carrier

Revision ID: 8e42eb6249e3
Revises: 71d859cb2452
Create Date: 2026-06-24 11:01:31.907569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e42eb6249e3'
down_revision: Union[str, Sequence[str], None] = '71d859cb2452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cab_types_master', sa.Column('roof_carrier', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cab_types_master', 'roof_carrier')
    # ### end Alembic commands ###
