"""remove-bearer-token-from-all-actors

Revision ID: 927acd1a8ead
Revises: 8a563743980f
Create Date: 2026-08-12 00:04:54.789148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '927acd1a8ead'
down_revision: Union[str, Sequence[str], None] = '8a563743980f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'bearer_token')
    op.drop_column('users', 'bearer_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bearer_token', mysql.TEXT(), nullable=True))
    op.add_column('drivers', sa.Column('bearer_token', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
