"""db-changes-05-03-v2

Revision ID: 993f78cad9d6
Revises: 0f8292e8a572
Create Date: 2026-03-05 02:06:43.540455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '993f78cad9d6'
down_revision: Union[str, Sequence[str], None] = '0f8292e8a572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_status_audits', 'changed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_status_audits', sa.Column('changed_by', mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'), nullable=True))
    # ### end Alembic commands ###
