"""db-changes-03-06

Revision ID: a375d73885c0
Revises: 993f78cad9d6
Create Date: 2026-03-06 01:16:23.411715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a375d73885c0'
down_revision: Union[str, Sequence[str], None] = '993f78cad9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('dispute_type', sa.Enum('fare', 'service', 'other', name='disputetypeenum'), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('raised_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=True)
    op.add_column('refunds', sa.Column('refund_trigger', sa.Enum('manual', 'automatic', name='refundtrigger'), nullable=True))
    op.add_column('refunds', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('refunds', 'refund_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               existing_nullable=True)
    op.alter_column('refunds', 'refund_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('full', 'partial', 'other', name='refundtype'),
               nullable=False)
    op.add_column('trips', sa.Column('dispute_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'trips', ['dispute_id'])
    op.create_foreign_key(None, 'trips', 'disputes', ['dispute_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_column('trips', 'dispute_id')
    op.alter_column('refunds', 'refund_type',
               existing_type=sa.Enum('full', 'partial', 'other', name='refundtype'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('refunds', 'refund_status',
               existing_type=sa.Enum('pending', 'completed', 'failed', 'unknown', name='refundstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('refunds', 'is_active')
    op.drop_column('refunds', 'refund_trigger')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_table('disputes')
    # ### end Alembic commands ###
