"""changes_to_driver_orm

Revision ID: a430ab6942b9
Revises: 7af32cc504c8
Create Date: 2026-08-01 17:16:06.509943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a430ab6942b9'
down_revision: Union[str, Sequence[str], None] = '7af32cc504c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('secondary_phone', sa.String(length=32), nullable=True))
    op.add_column('drivers', sa.Column('capacity', sa.String(length=32), nullable=True))
    op.add_column('drivers', sa.Column('color', sa.String(length=32), nullable=True))
    op.add_column('drivers', sa.Column('roof_carrier_available', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'drivers', ['secondary_phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'roof_carrier_available')
    op.drop_column('drivers', 'color')
    op.drop_column('drivers', 'capacity')
    op.drop_column('drivers', 'secondary_phone')
    # ### end Alembic commands ###
