"""unique-constraint-driver-rating

Revision ID: ac9e82e74c3c
Revises: bb343b3df63f
Create Date: 2026-03-26 02:26:37.291138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9e82e74c3c'
down_revision: Union[str, Sequence[str], None] = 'bb343b3df63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_ratings', sa.Column('overall_experience', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_driver_trip_customer_rating', 'driver_ratings', ['driver_id', 'trip_id', 'customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_driver_trip_customer_rating', 'driver_ratings', type_='unique')
    op.drop_column('driver_ratings', 'overall_experience')
    # ### end Alembic commands ###
