"""remove_outstanding_due_tbl__27022026

Revision ID: b745a15bd3f7
Revises: 02c82e459735
Create Date: 2026-02-27 02:13:21.753580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b745a15bd3f7'
down_revision: Union[str, Sequence[str], None] = '02c82e459735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outstanding_dues_id'), table_name='outstanding_dues')
    op.drop_table('outstanding_dues')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outstanding_dues',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_by', mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('outstanding_dues_ibfk_2')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('outstanding_dues_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_outstanding_dues_id'), 'outstanding_dues', ['id'], unique=False)
    # ### end Alembic commands ###
