"""convert_timestamps_to_utc_across_tbls

Revision ID: bb343b3df63f
Revises: bddaa82fd81c
Create Date: 2026-03-24 00:25:34.258708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bb343b3df63f'
down_revision: Union[str, Sequence[str], None] = 'bddaa82fd81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airports_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('airports_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('cab_types_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('cab_types_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(utc_timestamp())'))
    op.alter_column('disputes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('disputes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fuel_types_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('fuel_types_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('outstation_cab_pricing', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pre_onboarding_customers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(utc_timestamp())'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pre_onboarding_customers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(utc_timestamp())'))
    op.alter_column('outstation_cab_pricing', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fuel_types_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('fuel_types_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('disputes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('disputes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('customers', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(utc_timestamp())'))
    op.alter_column('cab_types_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('cab_types_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('airports_master', 'last_modified',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('airports_master', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    # ### end Alembic commands ###
