"""added_is_active_on_ttrip_type_config

Revision ID: bed92b8bfa47
Revises: bdec95cadbc3
Create Date: 2026-02-22 22:43:00.820797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed92b8bfa47'
down_revision: Union[str, Sequence[str], None] = 'bdec95cadbc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_package_config', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_package_config', 'is_active')
    # ### end Alembic commands ###
