"""db-changes-31726-created_by_type_changes

Revision ID: c0adf98e05af
Revises: 547fd8fa623c
Create Date: 2026-03-17 18:32:21.364941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c0adf98e05af'
down_revision: Union[str, Sequence[str], None] = '547fd8fa623c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('airport_cab_pricing', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('airports_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('cab_types_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('countries_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('fixed_platform_pricing', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('fuel_types_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('kyc_document_types', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('local_cab_pricing', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('night_pricing_config', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('outstation_cab_pricing', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('passengers', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('permit_fee_config', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('regions_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('states_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('trip_package_config', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('trip_types_master', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('tripwise_pricing_config', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'created_by',
               existing_type=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('tripwise_pricing_config', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('trip_types_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('trip_package_config', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('states_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('regions_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('permit_fee_config', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('passengers', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('outstation_cab_pricing', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('night_pricing_config', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('local_cab_pricing', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('kyc_document_types', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('fuel_types_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('fixed_platform_pricing', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('countries_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('cab_types_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('airports_master', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    op.alter_column('airport_cab_pricing', 'created_by',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.ENUM('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'system', 'customer', 'driver'),
               existing_nullable=False)
    # ### end Alembic commands ###
