"""threshold-columns

Revision ID: cada1a621bf5
Revises: 
Create Date: 2026-04-18 16:14:45.455606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cada1a621bf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outstation_cab_pricing', sa.Column('max_days_allowed', sa.Integer(), nullable=False, comment='Max 7 days allowed for outstation trips'))
    op.add_column('tripwise_pricing_config', sa.Column('min_distance_km', sa.Float(), nullable=True))
    op.add_column('tripwise_pricing_config', sa.Column('max_distance_km', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'max_distance_km')
    op.drop_column('tripwise_pricing_config', 'min_distance_km')
    op.drop_column('outstation_cab_pricing', 'max_days_allowed')
    # ### end Alembic commands ###
