"""rename_col_in_cancelation_policy_tbl__27022026

Revision ID: ccbd163ed9e0
Revises: b745a15bd3f7
Create Date: 2026-02-27 02:23:17.004732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ccbd163ed9e0'
down_revision: Union[str, Sequence[str], None] = 'b745a15bd3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation_policies', sa.Column('refund_percentage', sa.Float(), nullable=False))
    op.drop_column('cancellation_policies', 'cancelation_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation_policies', sa.Column('cancelation_amount', mysql.FLOAT(), nullable=False))
    op.drop_column('cancellation_policies', 'refund_percentage')
    # ### end Alembic commands ###
