"""initdb2105

Revision ID: cd6868c5838f
Revises: 0e290c77721d
Create Date: 2026-05-21 00:15:23.978701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6868c5838f'
down_revision: Union[str, Sequence[str], None] = '0e290c77721d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tripwise_pricing_config', sa.Column('prior_booking_window_hours', sa.Float(), nullable=True, comment='The prior booking window in hours for this trip type in this region or state. This helps ensure that customers book their trips in advance to help us manage our fleet and operations better, especially for outstation trips which require more planning and resources.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'prior_booking_window_hours')
    # ### end Alembic commands ###
