"""db-changes-41926-2

Revision ID: d2d984f231a8
Revises: 56a94caf7c9f
Create Date: 2026-04-19 18:09:45.831473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd2d984f231a8'
down_revision: Union[str, Sequence[str], None] = '56a94caf7c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_recent_locations',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False, comment='Full location details as returned by the geocoding API, stored as JSON for flexibility'),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'place_id', name='unique_user_place'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_user_recent', 'customer_recent_locations', ['customer_id', 'last_used_at'], unique=False)
    op.create_index(op.f('ix_customer_recent_locations_customer_id'), 'customer_recent_locations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_recent_locations_place_id'), 'customer_recent_locations', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_recent_locations_place_id'), table_name='customer_recent_locations')
    op.drop_index(op.f('ix_customer_recent_locations_customer_id'), table_name='customer_recent_locations')
    op.drop_index('idx_user_recent', table_name='customer_recent_locations')
    op.drop_table('customer_recent_locations')
    # ### end Alembic commands ###
