"""initdb

Revision ID: d4e58a49cda2
Revises: 
Create Date: 2026-08-22 14:41:30.231174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4e58a49cda2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports_master',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('iata_code', sa.String(length=8), nullable=True),
    sa.Column('icao_code', sa.String(length=8), nullable=True),
    sa.Column('elevation_ft', sa.String(length=16), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('dst', sa.String(length=8), nullable=True),
    sa.Column('tz_database_time_zone', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('place_id', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('state_code', sa.String(length=8), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('is_serviceable', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_index(op.f('ix_airports_master_region_code'), 'airports_master', ['region_code'], unique=False)
    op.create_table('cab_types_master',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.Enum('hatchback', 'sedan', 'sedan_plus', 'suv', 'suv_plus', name='cartypeenum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=20), nullable=True),
    sa.Column('passenger_capacity', sa.Integer(), nullable=True),
    sa.Column('luggage_capacity', sa.JSON(), nullable=True),
    sa.Column('roof_carrier', sa.Boolean(), nullable=True),
    sa.Column('cab_names', sa.JSON(), nullable=True),
    sa.Column('inventory_cab_names', sa.JSON(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cab_types_master_id'), 'cab_types_master', ['id'], unique=True)
    op.create_table('countries_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('phone_code', sa.String(length=8), nullable=False),
    sa.Column('phone_number_regex', sa.String(length=255), nullable=False),
    sa.Column('phone_min_length', sa.Integer(), nullable=False),
    sa.Column('phone_max_length', sa.Integer(), nullable=False),
    sa.Column('phone_example', sa.String(length=32), nullable=True),
    sa.Column('postal_code_regex', sa.String(length=255), nullable=False),
    sa.Column('postal_code_example', sa.String(length=32), nullable=True),
    sa.Column('postal_code_min_length', sa.Integer(), nullable=False),
    sa.Column('postal_code_max_length', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('currency_symbol', sa.String(length=8), nullable=False),
    sa.Column('currency_decimal_places', sa.Integer(), nullable=False),
    sa.Column('currency_in_words', sa.String(length=32), nullable=False),
    sa.Column('currency_international_name', sa.String(length=32), nullable=False),
    sa.Column('currency_symbol_position', sa.String(length=8), nullable=False),
    sa.Column('currency_code_position', sa.String(length=8), nullable=False),
    sa.Column('currency_thousand_separator', sa.String(length=8), nullable=False),
    sa.Column('currency_decimal_separator', sa.String(length=8), nullable=False),
    sa.Column('currency_lowest_unit_name', sa.String(length=32), nullable=False),
    sa.Column('currency_lowest_unit_conversion_factor', sa.Integer(), nullable=False),
    sa.Column('distance_unit', sa.String(length=8), nullable=True),
    sa.Column('flag', sa.String(length=8), nullable=False),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('min_age_for_drivers', sa.Integer(), nullable=False),
    sa.Column('min_age_for_customers', sa.Integer(), nullable=False),
    sa.Column('max_age_for_drivers', sa.Integer(), nullable=False),
    sa.Column('max_age_for_customers', sa.Integer(), nullable=False),
    sa.Column('min_age_for_system_users', sa.Integer(), nullable=False),
    sa.Column('max_age_for_system_users', sa.Integer(), nullable=False),
    sa.Column('is_serviceable', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code'),
    sa.UniqueConstraint('country_name'),
    sa.UniqueConstraint('currency'),
    sa.UniqueConstraint('currency_in_words'),
    sa.UniqueConstraint('currency_international_name'),
    sa.UniqueConstraint('currency_lowest_unit_name'),
    sa.UniqueConstraint('currency_symbol'),
    sa.UniqueConstraint('distance_unit'),
    sa.UniqueConstraint('flag'),
    sa.UniqueConstraint('locale'),
    sa.UniqueConstraint('phone_code'),
    sa.UniqueConstraint('time_zone')
    )
    op.create_index(op.f('ix_countries_master_id'), 'countries_master', ['id'], unique=True)
    op.create_table('customers',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'transgender', 'prefer_not_to_disclose', name='gender_enum'), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('opt_in_updates', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False, comment='Indicates if the customer is suspended from using the service due to policy violations or other disputes and issues.'),
    sa.Column('suspension_reason', sa.Text(), nullable=True, comment='If the customer is suspended, this field can store the reason for suspension.'),
    sa.Column('s3_image_info', sa.JSON(), nullable=True, comment="Stores S3 key and URL for the customer's profile picture if using S3 for storage."),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_customers_active_created', 'customers', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.create_index('ix_customers_verification_flags', 'customers', ['is_active', 'is_phone_verified', 'is_email_verified'], unique=False)
    op.create_table('drivers',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('secondary_phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'transgender', 'prefer_not_to_disclose', name='gender_enum'), nullable=False),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.Enum('indian', 'american', 'british', 'australian', 'canadian', 'other', name='nationalityenum'), nullable=True),
    sa.Column('religion', sa.Enum('hindu', 'muslim', 'christian', 'sikh', 'buddhist', 'jain', 'other', 'prefer_not_to_disclose', name='religionenum'), nullable=True),
    sa.Column('address', sa.JSON(), nullable=True),
    sa.Column('cab_type', sa.Enum('hatchback', 'sedan', 'sedan_plus', 'suv', 'suv_plus', name='cartypeenum'), nullable=False),
    sa.Column('fuel_type', sa.Enum('diesel', 'petrol', 'cng', name='fueltypeenum'), nullable=False),
    sa.Column('cab_model_and_make', sa.String(length=255), nullable=False),
    sa.Column('cab_registration_number', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('roof_carrier_available', sa.Boolean(), nullable=False),
    sa.Column('cab_amenities', sa.JSON(), nullable=True),
    sa.Column('payment_mode', sa.Enum('gpay', 'phonepe', 'paytm', 'bank_transfer', name='paymentmodeenum'), nullable=False),
    sa.Column('payment_phone_number', sa.String(length=32), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('kyc_documents', sa.JSON(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('s3_image_info', sa.JSON(), nullable=True, comment="Stores S3 key and URL for the driver's profile picture if using S3 for storage."),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False, comment='ID of the user or system that created this record'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cab_registration_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('secondary_phone')
    )
    op.create_index('ix_drivers_active_available_created', 'drivers', ['is_active', 'is_available', 'created_at'], unique=False)
    op.create_index(op.f('ix_drivers_created_by'), 'drivers', ['created_by'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=True)
    op.create_index('ix_drivers_name', 'drivers', ['name'], unique=False)
    op.create_table('fuel_types_master',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.Enum('diesel', 'petrol', 'cng', name='fueltypeenum'), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fuel_types_master_id'), 'fuel_types_master', ['id'], unique=True)
    op.create_table('kyc_document_types',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('document_type', sa.Enum('aadhar_card', 'pan_card', 'driving_license', 'passport', 'voter_id', 'vehicle_registration_certificate', 'vehicle_insurance', 'pollution_certificate', 'fitness_certificate', 'bank_statement', 'utility_bill', name='kycdocumenttypeenum'), nullable=False),
    sa.Column('document_alias', sa.String(length=255), nullable=True),
    sa.Column('document_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the document type is active and can be used for KYC verification. Inactive types are not available for new document submissions but existing documents of that type remain unaffected.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type')
    )
    op.create_index(op.f('ix_kyc_document_types_id'), 'kyc_document_types', ['id'], unique=True)
    op.create_table('pre_onboarding_customers',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pre_onboarding_customers_otp_hash'), 'pre_onboarding_customers', ['otp_hash'], unique=False)
    op.create_index(op.f('ix_pre_onboarding_customers_phone_number'), 'pre_onboarding_customers', ['phone_number'], unique=True)
    op.create_index('ix_pre_onboarding_expires_at', 'pre_onboarding_customers', ['expires_at'], unique=False)
    op.create_table('seed_metadata',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('key', sa.Enum('INITIAL_SEED_COMPLETED', 'SEED_MASTER_DATA_V1', 'SEED_GEO_CORE_V1', 'SEED_GEO_REGIONS_V1', 'SEED_SUPPORT_CONTACTS_V1', 'SEED_PRICING_LOCAL_V1', 'SEED_PRICING_OUTSTATION_V1', 'SEED_PRICING_AIRPORT_V1', 'SEED_PRICING_PLATFORM_V1', 'SEED_PRICING_NIGHT_V1', 'SEED_PRICING_PERMIT_V1', 'SEED_PRICING_CANCELLATION_POLICY_V1', name='seed_key_enum'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_seed_metadata_key')
    )
    op.create_index(op.f('ix_seed_metadata_id'), 'seed_metadata', ['id'], unique=True)
    op.create_index(op.f('ix_seed_metadata_key'), 'seed_metadata', ['key'], unique=True)
    op.create_table('support_contacts',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('support_type', sa.Enum('customer', 'driver', 'booking', 'payment', 'emergency', 'general', name='customer_support_type_enum'), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_support_contacts_active_type_created', 'support_contacts', ['is_active', 'support_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_support_contacts_email'), 'support_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_support_contacts_id'), 'support_contacts', ['id'], unique=True)
    op.create_index(op.f('ix_support_contacts_is_active'), 'support_contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_contacts_phone_number'), 'support_contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_support_contacts_support_type'), 'support_contacts', ['support_type'], unique=False)
    op.create_table('temp_trips',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('creator_type', sa.Enum('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'regional_admin', 'state_admin', 'system', 'customer', 'driver', 'support_agent', name='roleenum'), nullable=False),
    sa.Column('trip_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('origin', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('hops', sa.JSON(), nullable=True),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('total_unique_states', sa.Integer(), nullable=True),
    sa.Column('unique_states', sa.JSON(), nullable=True),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('package_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('package_label', sa.String(length=255), nullable=True),
    sa.Column('package_label_short', sa.String(length=100), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('expected_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('included_kms', sa.Float(), nullable=True),
    sa.Column('rate_per_min', sa.Float(), nullable=True, comment='Applicable for hourly rental trips, this is the rate per minute for the trip which is used to calculate the final price for hourly rental trips based on the total duration of the trip. This field is populated based on the package chosen by the customer and the region-specific pricing configured in the system for that package and trip type.'),
    sa.Column('rate_per_km', sa.Float(), nullable=True, comment='Applicable for outstation trips, airport transfers, and hourly rental trips, this is the rate per km for the trip which is used to calculate the final price based on the total distance of the trip. This field is populated based on the package chosen by the customer and the region/state-specific pricing configured in the system for that package and trip type.'),
    sa.Column('num_adults', sa.Integer(), nullable=False),
    sa.Column('num_children', sa.Integer(), nullable=True),
    sa.Column('num_large_suitcases', sa.Integer(), nullable=True),
    sa.Column('num_carryons', sa.Integer(), nullable=True),
    sa.Column('num_backpacks', sa.Integer(), nullable=True),
    sa.Column('num_other_bags', sa.Integer(), nullable=True),
    sa.Column('num_luggages', sa.Integer(), nullable=True),
    sa.Column('num_passengers', sa.Integer(), nullable=True),
    sa.Column('preferred_car_type', sa.Enum('hatchback', 'sedan', 'sedan_plus', 'suv', 'suv_plus', name='cartypeenum'), nullable=True),
    sa.Column('preferred_fuel_type', sa.Enum('diesel', 'petrol', 'cng', name='fueltypeenum'), nullable=True),
    sa.Column('in_car_amenities', sa.JSON(), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=True),
    sa.Column('driver_allowance', sa.Float(), nullable=True),
    sa.Column('tolls', sa.Float(), nullable=True),
    sa.Column('parking', sa.Float(), nullable=True),
    sa.Column('permit_fee', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('final_display_price', sa.Float(), nullable=True),
    sa.Column('payment_provider_metadata', sa.JSON(), nullable=True),
    sa.Column('price_breakdown', sa.JSON(), nullable=True),
    sa.Column('overages', sa.JSON(), nullable=True),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('flight_number', sa.String(length=32), nullable=True),
    sa.Column('terminal_number', sa.String(length=32), nullable=True),
    sa.Column('toll_road_preferred', sa.Boolean(), nullable=False),
    sa.Column('placard_required', sa.Boolean(), nullable=True),
    sa.Column('placard_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_km', sa.Float(), nullable=True),
    sa.Column('indicative_overage_warning', sa.Boolean(), nullable=False),
    sa.Column('alternate_customer_phone', sa.String(length=32), nullable=True),
    sa.Column('passenger_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('utc_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('ix_temp_trips_creator_created', 'temp_trips', ['creator_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_temp_trips_creator_id'), 'temp_trips', ['creator_id'], unique=False)
    op.create_index(op.f('ix_temp_trips_id'), 'temp_trips', ['id'], unique=True)
    op.create_index(op.f('ix_temp_trips_package_id'), 'temp_trips', ['package_id'], unique=False)
    op.create_table('trip_types_master',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_type', sa.Enum('local', 'outstation', 'airport_pickup', 'airport_drop', 'airport_general', name='triptypeenum'), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_type')
    )
    op.create_index(op.f('ix_trip_types_master_id'), 'trip_types_master', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'regional_admin', 'state_admin', 'system', 'customer', 'driver', 'support_agent', name='user_role_enum'), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'transgender', 'prefer_not_to_disclose', name='gender_enum'), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('customer_email_verification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('verification_url', sa.String(length=512), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_url')
    )
    op.create_index(op.f('ix_customer_email_verification_customer_id'), 'customer_email_verification', ['customer_id'], unique=False)
    op.create_table('customer_recent_locations',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False, comment='Full location details as returned by the geocoding API, stored as JSON for flexibility'),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'place_id', name='unique_user_place'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_user_recent', 'customer_recent_locations', ['customer_id', 'last_used_at'], unique=False)
    op.create_index(op.f('ix_customer_recent_locations_customer_id'), 'customer_recent_locations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_recent_locations_place_id'), 'customer_recent_locations', ['place_id'], unique=False)
    op.create_table('customer_sessions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_customer_sessions_customer_id'), 'customer_sessions', ['customer_id'], unique=False)
    op.create_index('ix_customer_sessions_customer_id_is_active', 'customer_sessions', ['customer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_customer_sessions_expires_at'), 'customer_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_customer_sessions_token_hash'), 'customer_sessions', ['token_hash'], unique=True)
    op.create_table('fixed_platform_pricing',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('country_id', mysql.CHAR(length=36), nullable=True, comment='FK to countries_master; null means applies to all countries'),
    sa.Column('fixed_platform_fee', sa.Float(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixed_platform_pricing_country_id'), 'fixed_platform_pricing', ['country_id'], unique=True)
    op.create_index(op.f('ix_fixed_platform_pricing_id'), 'fixed_platform_pricing', ['id'], unique=True)
    op.create_table('passengers',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('ix_passengers_customer_active', 'passengers', ['customer_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_passengers_customer_id'), 'passengers', ['customer_id'], unique=False)
    op.create_table('states_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state_name', sa.String(length=128), nullable=False),
    sa.Column('state_code', sa.String(length=16), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('is_serviceable', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_name')
    )
    op.create_index(op.f('ix_states_master_country_id'), 'states_master', ['country_id'], unique=False)
    op.create_index(op.f('ix_states_master_id'), 'states_master', ['id'], unique=True)
    op.create_index(op.f('ix_states_master_state_code'), 'states_master', ['state_code'], unique=True)
    op.create_table('system_user_sessions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_sys_user_sessions_user_id_is_active', 'system_user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_system_user_sessions_expires_at'), 'system_user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_system_user_sessions_token_hash'), 'system_user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_system_user_sessions_user_id'), 'system_user_sessions', ['user_id'], unique=False)
    op.create_table('outstation_cab_pricing',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('cab_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fuel_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('base_fare_per_km', sa.Float(), nullable=False),
    sa.Column('driver_allowance_per_day', sa.Float(), nullable=False),
    sa.Column('min_included_km_per_day', sa.Integer(), nullable=False),
    sa.Column('is_available_in_network', sa.Boolean(), nullable=False),
    sa.Column('overage_amount_per_km', sa.Float(), nullable=False),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cab_type_id'], ['cab_types_master.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types_master.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'cab_type_id', 'fuel_type_id', name='uq_outstation_state_cab_fuel')
    )
    op.create_index(op.f('ix_outstation_cab_pricing_id'), 'outstation_cab_pricing', ['id'], unique=True)
    op.create_index('ix_outstation_pricing_available', 'outstation_cab_pricing', ['is_available_in_network'], unique=False)
    op.create_index('ix_outstation_pricing_state_available', 'outstation_cab_pricing', ['state_id', 'is_available_in_network'], unique=False)
    op.create_table('permit_fee_config',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('cab_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fuel_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('permit_fee', sa.Float(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cab_type_id'], ['cab_types_master.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types_master.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cab_type_id', 'fuel_type_id', 'state_id', name='uq_cab_fuel_state')
    )
    op.create_index(op.f('ix_permit_fee_config_id'), 'permit_fee_config', ['id'], unique=True)
    op.create_index('ix_permit_fee_state', 'permit_fee_config', ['state_id'], unique=False)
    op.create_table('regions_master',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('region_name', sa.String(length=64), nullable=False),
    sa.Column('alt_region_names', sa.JSON(), nullable=True),
    sa.Column('region_code', sa.String(length=8), nullable=False),
    sa.Column('alt_region_codes', sa.JSON(), nullable=True),
    sa.Column('state_id', sa.String(length=36), nullable=True),
    sa.Column('trip_types', sa.JSON(), nullable=True),
    sa.Column('fuel_types', sa.JSON(), nullable=True),
    sa.Column('car_types', sa.JSON(), nullable=True),
    sa.Column('airport_locations', sa.JSON(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('is_serviceable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code'),
    sa.UniqueConstraint('region_name')
    )
    op.create_index(op.f('ix_regions_master_country_id'), 'regions_master', ['country_id'], unique=False)
    op.create_index(op.f('ix_regions_master_id'), 'regions_master', ['id'], unique=True)
    op.create_index(op.f('ix_regions_master_state_id'), 'regions_master', ['state_id'], unique=False)
    op.create_table('airport_cab_pricing',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('cab_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fuel_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fare_per_km', sa.Float(), nullable=False),
    sa.Column('overage_amount_per_km', sa.Float(), nullable=False),
    sa.Column('is_available_in_network', sa.Boolean(), nullable=False),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cab_type_id'], ['cab_types_master.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types_master.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'cab_type_id', 'fuel_type_id', name='uq_airport_region_cab_fuel')
    )
    op.create_index(op.f('ix_airport_cab_pricing_id'), 'airport_cab_pricing', ['id'], unique=True)
    op.create_index('ix_airport_pricing_available', 'airport_cab_pricing', ['is_available_in_network'], unique=False)
    op.create_index('ix_airport_pricing_region_available', 'airport_cab_pricing', ['region_id', 'is_available_in_network'], unique=False)
    op.create_table('cancellation_policies',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('free_cutoff_minutes', sa.Integer(), nullable=False),
    sa.Column('free_cutoff_time_label', sa.String(length=50), nullable=True),
    sa.Column('refund_percentage', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ),
    sa.ForeignKeyConstraint(['trip_type_id'], ['trip_types_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_type_id', 'region_id', name='uq_policy_trip_type_region'),
    sa.UniqueConstraint('trip_type_id', 'state_id', name='uq_policy_trip_type_state')
    )
    op.create_index(op.f('ix_cancellation_policies_id'), 'cancellation_policies', ['id'], unique=True)
    op.create_index(op.f('ix_cancellation_policies_region_id'), 'cancellation_policies', ['region_id'], unique=False)
    op.create_index(op.f('ix_cancellation_policies_state_id'), 'cancellation_policies', ['state_id'], unique=False)
    op.create_index(op.f('ix_cancellation_policies_trip_type_id'), 'cancellation_policies', ['trip_type_id'], unique=False)
    op.create_table('local_cab_pricing',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('cab_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('fuel_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('overage_amount_per_hour', sa.Float(), nullable=False),
    sa.Column('overage_amount_per_km', sa.Float(), nullable=False),
    sa.Column('is_available_in_network', sa.Boolean(), nullable=False),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cab_type_id'], ['cab_types_master.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types_master.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', 'cab_type_id', 'fuel_type_id', name='uq_local_region_cab_fuel')
    )
    op.create_index(op.f('ix_local_cab_pricing_id'), 'local_cab_pricing', ['id'], unique=True)
    op.create_index('ix_local_pricing_available', 'local_cab_pricing', ['is_available_in_network'], unique=False)
    op.create_index('ix_local_pricing_region_available', 'local_cab_pricing', ['region_id', 'is_available_in_network'], unique=False)
    op.create_table('night_pricing_config',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('night_start_hour', sa.Integer(), nullable=False),
    sa.Column('night_end_hour', sa.Integer(), nullable=False),
    sa.Column('night_hours_label', sa.String(length=50), nullable=False),
    sa.Column('night_overage_amount_per_block', sa.Float(), nullable=False),
    sa.Column('night_block_hours', sa.Integer(), nullable=False),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id', name='uq_night_region'),
    sa.UniqueConstraint('state_id', name='uq_night_state')
    )
    op.create_index(op.f('ix_night_pricing_config_id'), 'night_pricing_config', ['id'], unique=True)
    op.create_table('support_routing_rules',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('support_contact_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('scope_type', sa.Enum('country', 'state', 'region', name='support_scope_enum'), nullable=False),
    sa.Column('scope_id', mysql.CHAR(length=36), nullable=False, comment='ID of the country, state, or region selected by scope_type.'),
    sa.Column('country_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('trip_type_scope', mysql.CHAR(length=36), nullable=False, comment="Use 'all' or a TripTypeEnum value such as local/outstation."),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Lower values win when multiple active support rules match.'),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("((scope_type = 'country' AND country_id = scope_id AND state_id IS NULL AND region_id IS NULL) OR (scope_type = 'state' AND state_id = scope_id AND country_id IS NULL AND region_id IS NULL) OR (scope_type = 'region' AND region_id = scope_id AND country_id IS NULL AND state_id IS NULL))", name='ck_support_rule_scope_matches_geography'),
    sa.ForeignKeyConstraint(['country_id'], ['countries_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_contact_id'], ['support_contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('support_contact_id', 'scope_type', 'scope_id', 'trip_type_scope', name='uq_support_contact_scope_trip_type')
    )
    op.create_index(op.f('ix_support_routing_rules_country_id'), 'support_routing_rules', ['country_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_id'), 'support_routing_rules', ['id'], unique=True)
    op.create_index(op.f('ix_support_routing_rules_is_active'), 'support_routing_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_region_id'), 'support_routing_rules', ['region_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_scope_id'), 'support_routing_rules', ['scope_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_scope_type'), 'support_routing_rules', ['scope_type'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_state_id'), 'support_routing_rules', ['state_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_support_contact_id'), 'support_routing_rules', ['support_contact_id'], unique=False)
    op.create_index(op.f('ix_support_routing_rules_trip_type_scope'), 'support_routing_rules', ['trip_type_scope'], unique=False)
    op.create_index('ix_support_rule_lookup', 'support_routing_rules', ['is_active', 'scope_type', 'scope_id', 'trip_type_scope', 'priority'], unique=False)
    op.create_table('trip_package_config',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True, comment='FK to regions_master; null means applies to all regions'),
    sa.Column('included_hours', sa.Integer(), nullable=False),
    sa.Column('included_km', sa.Integer(), nullable=False),
    sa.Column('driver_allowance', sa.Float(), nullable=True),
    sa.Column('package_label', sa.String(length=64), nullable=False),
    sa.Column('best_intended_for', sa.Text(), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.ForeignKeyConstraint(['trip_type_id'], ['trip_types_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_package_config_id'), 'trip_package_config', ['id'], unique=True)
    op.create_index(op.f('ix_trip_package_config_region_id'), 'trip_package_config', ['region_id'], unique=False)
    op.create_index(op.f('ix_trip_package_config_trip_type_id'), 'trip_package_config', ['trip_type_id'], unique=False)
    op.create_index('ix_trip_package_region', 'trip_package_config', ['trip_type_id', 'region_id', 'package_label'], unique=True)
    op.create_table('tripwise_pricing_config',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('dynamic_platform_fee_percent', sa.Float(), nullable=False),
    sa.Column('min_included_hours', sa.Integer(), nullable=True),
    sa.Column('max_included_hours', sa.Integer(), nullable=True),
    sa.Column('min_included_km', sa.Integer(), nullable=True),
    sa.Column('max_included_km', sa.Integer(), nullable=True),
    sa.Column('min_platform_fee', sa.Float(), nullable=True, comment='Minimum platform fee charged to customer for this trip type in this region or state, regardless of total fare. This helps ensure that we cover our costs for low-fare trips.'),
    sa.Column('max_platform_fee', sa.Float(), nullable=True, comment='Maximum platform fee charged to customer for this trip type in this region or state, regardless of total fare. This helps ensure that we do not overcharge for high-fare trips.'),
    sa.Column('min_outbound_distance_km', sa.Float(), nullable=True),
    sa.Column('max_distance_km', sa.Float(), nullable=True),
    sa.Column('min_days_allowed', sa.Integer(), nullable=True, comment='Min days allowed for outstation trips'),
    sa.Column('max_days_allowed', sa.Integer(), nullable=True, comment='Max days allowed for outstation trips'),
    sa.Column('max_hops_allowed', sa.Integer(), nullable=True, comment='Max hops/stops allowed for outstation trips'),
    sa.Column('placard_charge', sa.Float(), nullable=True),
    sa.Column('overage_warning_km_threshold', sa.Float(), nullable=True),
    sa.Column('toll', sa.Float(), nullable=True),
    sa.Column('parking', sa.Float(), nullable=True),
    sa.Column('prior_booking_window_hours', sa.Float(), nullable=True, comment='The prior booking window in hours for this trip type in this region or state. This helps ensure that customers book their trips in advance to help us manage our fleet and operations better, especially for outstation trips which require more planning and resources.'),
    sa.Column('region_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('state_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions_master.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states_master.id'], ),
    sa.ForeignKeyConstraint(['trip_type_id'], ['trip_types_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_type_id', 'region_id', name='uq_trip_region'),
    sa.UniqueConstraint('trip_type_id', 'state_id', name='uq_trip_state')
    )
    op.create_index(op.f('ix_tripwise_pricing_config_id'), 'tripwise_pricing_config', ['id'], unique=True)
    op.create_table('trips',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('creator_type', sa.Enum('super_admin', 'driver_admin', 'finance_admin', 'customer_admin', 'regional_admin', 'state_admin', 'system', 'customer', 'driver', 'support_agent', name='roleenum'), nullable=False),
    sa.Column('trip_type_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('origin', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('hops', sa.JSON(), nullable=True),
    sa.Column('is_interstate', sa.Boolean(), nullable=False),
    sa.Column('total_unique_states', sa.Integer(), nullable=True),
    sa.Column('unique_states', sa.JSON(), nullable=True),
    sa.Column('is_round_trip', sa.Boolean(), nullable=False),
    sa.Column('package_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('package_label', sa.String(length=255), nullable=True),
    sa.Column('package_label_short', sa.String(length=100), nullable=True),
    sa.Column('rate_per_min', sa.Float(), nullable=True, comment='Applicable for hourly rental trips, this is the rate per minute for the trip which is used to calculate the final price for hourly rental trips based on the total duration of the trip. This field is populated based on the package chosen by the customer and the region-specific pricing configured in the system for that package and trip type.'),
    sa.Column('rate_per_km', sa.Float(), nullable=True, comment='Applicable for outstation trips, airport transfers, and hourly rental trips, this is the rate per km for the trip which is used to calculate the final price based on the total distance of the trip. This field is populated based on the package chosen by the customer and the region/state-specific pricing configured in the system for that package and trip type.'),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('expected_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('included_kms', sa.Float(), nullable=True),
    sa.Column('num_adults', sa.Integer(), nullable=False),
    sa.Column('num_children', sa.Integer(), nullable=True),
    sa.Column('num_large_suitcases', sa.Integer(), nullable=True),
    sa.Column('num_carryons', sa.Integer(), nullable=True),
    sa.Column('num_backpacks', sa.Integer(), nullable=True),
    sa.Column('num_other_bags', sa.Integer(), nullable=True),
    sa.Column('num_luggages', sa.Integer(), nullable=True),
    sa.Column('num_passengers', sa.Integer(), nullable=True),
    sa.Column('preferred_car_type', sa.Enum('hatchback', 'sedan', 'sedan_plus', 'suv', 'suv_plus', name='cartypeenum'), nullable=True),
    sa.Column('preferred_fuel_type', sa.Enum('diesel', 'petrol', 'cng', name='fueltypeenum'), nullable=True),
    sa.Column('in_car_amenities', sa.JSON(), nullable=True),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('status', sa.Enum('created', 'pending', 'confirmed', 'ongoing', 'completed', 'cancelled', 'dispute', name='tripstatusenum'), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=True),
    sa.Column('driver_allowance', sa.Float(), nullable=True),
    sa.Column('tolls', sa.Float(), nullable=True),
    sa.Column('parking', sa.Float(), nullable=True),
    sa.Column('permit_fee', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('final_display_price', sa.Float(), nullable=True),
    sa.Column('advance_payment', sa.Float(), nullable=True),
    sa.Column('balance_payment', sa.Float(), nullable=True),
    sa.Column('payment_provider_metadata', sa.JSON(), nullable=True),
    sa.Column('price_breakdown', sa.JSON(), nullable=True),
    sa.Column('overages', sa.JSON(), nullable=True),
    sa.Column('inclusions', sa.JSON(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('flight_number', sa.String(length=32), nullable=True),
    sa.Column('terminal_number', sa.String(length=32), nullable=True),
    sa.Column('toll_road_preferred', sa.Boolean(), nullable=False),
    sa.Column('placard_required', sa.Boolean(), nullable=True),
    sa.Column('placard_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('special_needs_requests', sa.Text(), nullable=True),
    sa.Column('estimated_km', sa.Float(), nullable=True),
    sa.Column('indicative_overage_warning', sa.Boolean(), nullable=False),
    sa.Column('alternate_customer_phone', sa.String(length=32), nullable=True),
    sa.Column('passenger_id', mysql.CHAR(length=36), nullable=True, comment='FK to passengers table; null if trip is for self'),
    sa.Column('upgradation_information', sa.JSON(), nullable=True, comment='JSON/text for upgradation information, if any. This is applicable for scenarios where Cabbo upgrades the trip to a higher car type and/or fuel type or others. The upgradation information will be stored in this field as a JSON object with details of the upgradation and the additional charges, if any.'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('utc_offset', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['trip_package_config.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_type_id'], ['trip_types_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_active_created', 'trips', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_trips_active_status_created', 'trips', ['is_active', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_trips_booking_id'), 'trips', ['booking_id'], unique=True)
    op.create_index(op.f('ix_trips_creator_id'), 'trips', ['creator_id'], unique=False)
    op.create_index('ix_trips_customer_bucket', 'trips', ['creator_id', 'creator_type', 'is_active', 'status', 'start_datetime'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_driver_status', 'trips', ['driver_id', 'is_active', 'status'], unique=False)
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=True)
    op.create_index(op.f('ix_trips_package_id'), 'trips', ['package_id'], unique=False)
    op.create_index(op.f('ix_trips_passenger_id'), 'trips', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_trips_trip_type_id'), 'trips', ['trip_type_id'], unique=False)
    op.create_index('ix_trips_type_status_start', 'trips', ['trip_type_id', 'status', 'start_datetime'], unique=False)
    op.create_table('disputes',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('dispute_type', sa.Enum('fare', 'service', 'other', 'unknown', name='disputetypeenum'), nullable=False, comment='Type of dispute, e.g., fare, service, etc.'),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('raised_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatusenum'), nullable=False),
    sa.Column('dispute_trigger', sa.Enum('manual', 'automatic', name='disputetriggerenum'), nullable=True, comment="Description of how the dispute was triggered, e.g., 'manual', 'automatic'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_index('ix_disputes_active_status_created', 'disputes', ['is_active', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=True)
    op.create_table('driver_earnings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('earnings', sa.Float(), nullable=False),
    sa.Column('extra_earnings', sa.Float(), nullable=True),
    sa.Column('extra_earnings_breakdown', sa.JSON(), nullable=True),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=False, comment='ID of the user or system that created this record'),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'trip_id', name='uq_driver_trip_earning'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index(op.f('ix_driver_earnings_created_by'), 'driver_earnings', ['created_by'], unique=False)
    op.create_index('ix_driver_earnings_driver_active_created', 'driver_earnings', ['driver_id', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_driver_earnings_id'), 'driver_earnings', ['id'], unique=True)
    op.create_table('refunds',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=255), nullable=True),
    sa.Column('refund_status', sa.Enum('initiated', 'processed', 'pending', 'completed', 'failed', 'unknown', name='refundstatus'), nullable=True, comment='Status of the refund transaction from the payment provider, e.g., pending, completed, failed, etc.'),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_description', sa.Text(), nullable=False),
    sa.Column('refund_details', sa.JSON(), nullable=True),
    sa.Column('refund_initiated_datetime', sa.DateTime(), nullable=True),
    sa.Column('refund_retried_datetime', sa.DateTime(), nullable=True),
    sa.Column('refund_type', sa.Enum('full', 'partial', 'other', name='refundtype'), nullable=False),
    sa.Column('refund_provider', sa.Enum('razorpay', 'stripe', 'phonepe', name='paymentprovider'), nullable=True, comment='Payment provider used for processing the refund, e.g., Stripe, PayPal, etc.'),
    sa.Column('refund_trigger', sa.Enum('manual', 'automatic', name='refundtrigger'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', mysql.CHAR(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refunds_active_status_created', 'refunds', ['is_active', 'refund_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_refunds_entity_id'), 'refunds', ['entity_id'], unique=True)
    op.create_index(op.f('ix_refunds_id'), 'refunds', ['id'], unique=True)
    op.create_index(op.f('ix_refunds_policy_id'), 'refunds', ['policy_id'], unique=False)
    op.create_table('trip_cancellations',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('entity_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('canceled_by', mysql.CHAR(length=36), nullable=False),
    sa.Column('cancellation_sub_status', sa.Enum('none', 'customer_cancelled', 'customer_no_show', 'driver_cancelled', 'driver_unavailable', 'driver_no_show', 'other', name='cancellation_sub_status_enum'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trip_cancellations_active_created', 'trip_cancellations', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_trip_cancellations_entity_id'), 'trip_cancellations', ['entity_id'], unique=True)
    op.create_index(op.f('ix_trip_cancellations_id'), 'trip_cancellations', ['id'], unique=True)
    op.create_table('trip_ratings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('feedback', sa.String(length=500), nullable=True),
    sa.Column('overall_experience', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'trip_id', 'customer_id', name='uq_driver_trip_customer_rating')
    )
    op.create_index('ix_trip_ratings_customer_flagged', 'trip_ratings', ['customer_id', 'is_flagged'], unique=False)
    op.create_index('ix_trip_ratings_driver_flagged', 'trip_ratings', ['driver_id', 'is_flagged'], unique=False)
    op.create_index(op.f('ix_trip_ratings_id'), 'trip_ratings', ['id'], unique=True)
    op.create_table('trip_status_audits',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'confirmed', 'ongoing', 'completed', 'cancelled', 'dispute', name='tripstatusenum'), nullable=False),
    sa.Column('committer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_status_audits_committer_id'), 'trip_status_audits', ['committer_id'], unique=False)
    op.create_index(op.f('ix_trip_status_audits_id'), 'trip_status_audits', ['id'], unique=True)
    op.create_index('ix_trip_status_audits_trip_timestamp', 'trip_status_audits', ['trip_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trip_status_audits_trip_timestamp', table_name='trip_status_audits')
    op.drop_index(op.f('ix_trip_status_audits_id'), table_name='trip_status_audits')
    op.drop_index(op.f('ix_trip_status_audits_committer_id'), table_name='trip_status_audits')
    op.drop_table('trip_status_audits')
    op.drop_index(op.f('ix_trip_ratings_id'), table_name='trip_ratings')
    op.drop_index('ix_trip_ratings_driver_flagged', table_name='trip_ratings')
    op.drop_index('ix_trip_ratings_customer_flagged', table_name='trip_ratings')
    op.drop_table('trip_ratings')
    op.drop_index(op.f('ix_trip_cancellations_id'), table_name='trip_cancellations')
    op.drop_index(op.f('ix_trip_cancellations_entity_id'), table_name='trip_cancellations')
    op.drop_index('ix_trip_cancellations_active_created', table_name='trip_cancellations')
    op.drop_table('trip_cancellations')
    op.drop_index(op.f('ix_refunds_policy_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_entity_id'), table_name='refunds')
    op.drop_index('ix_refunds_active_status_created', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_driver_earnings_id'), table_name='driver_earnings')
    op.drop_index('ix_driver_earnings_driver_active_created', table_name='driver_earnings')
    op.drop_index(op.f('ix_driver_earnings_created_by'), table_name='driver_earnings')
    op.drop_table('driver_earnings')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_index('ix_disputes_active_status_created', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_trips_type_status_start', table_name='trips')
    op.drop_index(op.f('ix_trips_trip_type_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_passenger_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_package_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_index('ix_trips_driver_status', table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index('ix_trips_customer_bucket', table_name='trips')
    op.drop_index(op.f('ix_trips_creator_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_booking_id'), table_name='trips')
    op.drop_index('ix_trips_active_status_created', table_name='trips')
    op.drop_index('ix_trips_active_created', table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_tripwise_pricing_config_id'), table_name='tripwise_pricing_config')
    op.drop_table('tripwise_pricing_config')
    op.drop_index('ix_trip_package_region', table_name='trip_package_config')
    op.drop_index(op.f('ix_trip_package_config_trip_type_id'), table_name='trip_package_config')
    op.drop_index(op.f('ix_trip_package_config_region_id'), table_name='trip_package_config')
    op.drop_index(op.f('ix_trip_package_config_id'), table_name='trip_package_config')
    op.drop_table('trip_package_config')
    op.drop_index('ix_support_rule_lookup', table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_trip_type_scope'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_support_contact_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_state_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_scope_type'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_scope_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_region_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_is_active'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_id'), table_name='support_routing_rules')
    op.drop_index(op.f('ix_support_routing_rules_country_id'), table_name='support_routing_rules')
    op.drop_table('support_routing_rules')
    op.drop_index(op.f('ix_night_pricing_config_id'), table_name='night_pricing_config')
    op.drop_table('night_pricing_config')
    op.drop_index('ix_local_pricing_region_available', table_name='local_cab_pricing')
    op.drop_index('ix_local_pricing_available', table_name='local_cab_pricing')
    op.drop_index(op.f('ix_local_cab_pricing_id'), table_name='local_cab_pricing')
    op.drop_table('local_cab_pricing')
    op.drop_index(op.f('ix_cancellation_policies_trip_type_id'), table_name='cancellation_policies')
    op.drop_index(op.f('ix_cancellation_policies_state_id'), table_name='cancellation_policies')
    op.drop_index(op.f('ix_cancellation_policies_region_id'), table_name='cancellation_policies')
    op.drop_index(op.f('ix_cancellation_policies_id'), table_name='cancellation_policies')
    op.drop_table('cancellation_policies')
    op.drop_index('ix_airport_pricing_region_available', table_name='airport_cab_pricing')
    op.drop_index('ix_airport_pricing_available', table_name='airport_cab_pricing')
    op.drop_index(op.f('ix_airport_cab_pricing_id'), table_name='airport_cab_pricing')
    op.drop_table('airport_cab_pricing')
    op.drop_index(op.f('ix_regions_master_state_id'), table_name='regions_master')
    op.drop_index(op.f('ix_regions_master_id'), table_name='regions_master')
    op.drop_index(op.f('ix_regions_master_country_id'), table_name='regions_master')
    op.drop_table('regions_master')
    op.drop_index('ix_permit_fee_state', table_name='permit_fee_config')
    op.drop_index(op.f('ix_permit_fee_config_id'), table_name='permit_fee_config')
    op.drop_table('permit_fee_config')
    op.drop_index('ix_outstation_pricing_state_available', table_name='outstation_cab_pricing')
    op.drop_index('ix_outstation_pricing_available', table_name='outstation_cab_pricing')
    op.drop_index(op.f('ix_outstation_cab_pricing_id'), table_name='outstation_cab_pricing')
    op.drop_table('outstation_cab_pricing')
    op.drop_index(op.f('ix_system_user_sessions_user_id'), table_name='system_user_sessions')
    op.drop_index(op.f('ix_system_user_sessions_token_hash'), table_name='system_user_sessions')
    op.drop_index(op.f('ix_system_user_sessions_expires_at'), table_name='system_user_sessions')
    op.drop_index('ix_sys_user_sessions_user_id_is_active', table_name='system_user_sessions')
    op.drop_table('system_user_sessions')
    op.drop_index(op.f('ix_states_master_state_code'), table_name='states_master')
    op.drop_index(op.f('ix_states_master_id'), table_name='states_master')
    op.drop_index(op.f('ix_states_master_country_id'), table_name='states_master')
    op.drop_table('states_master')
    op.drop_index(op.f('ix_passengers_customer_id'), table_name='passengers')
    op.drop_index('ix_passengers_customer_active', table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_fixed_platform_pricing_id'), table_name='fixed_platform_pricing')
    op.drop_index(op.f('ix_fixed_platform_pricing_country_id'), table_name='fixed_platform_pricing')
    op.drop_table('fixed_platform_pricing')
    op.drop_index(op.f('ix_customer_sessions_token_hash'), table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_expires_at'), table_name='customer_sessions')
    op.drop_index('ix_customer_sessions_customer_id_is_active', table_name='customer_sessions')
    op.drop_index(op.f('ix_customer_sessions_customer_id'), table_name='customer_sessions')
    op.drop_table('customer_sessions')
    op.drop_index(op.f('ix_customer_recent_locations_place_id'), table_name='customer_recent_locations')
    op.drop_index(op.f('ix_customer_recent_locations_customer_id'), table_name='customer_recent_locations')
    op.drop_index('idx_user_recent', table_name='customer_recent_locations')
    op.drop_table('customer_recent_locations')
    op.drop_index(op.f('ix_customer_email_verification_customer_id'), table_name='customer_email_verification')
    op.drop_table('customer_email_verification')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trip_types_master_id'), table_name='trip_types_master')
    op.drop_table('trip_types_master')
    op.drop_index(op.f('ix_temp_trips_package_id'), table_name='temp_trips')
    op.drop_index(op.f('ix_temp_trips_id'), table_name='temp_trips')
    op.drop_index(op.f('ix_temp_trips_creator_id'), table_name='temp_trips')
    op.drop_index('ix_temp_trips_creator_created', table_name='temp_trips')
    op.drop_table('temp_trips')
    op.drop_index(op.f('ix_support_contacts_support_type'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_phone_number'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_is_active'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_id'), table_name='support_contacts')
    op.drop_index(op.f('ix_support_contacts_email'), table_name='support_contacts')
    op.drop_index('ix_support_contacts_active_type_created', table_name='support_contacts')
    op.drop_table('support_contacts')
    op.drop_index(op.f('ix_seed_metadata_key'), table_name='seed_metadata')
    op.drop_index(op.f('ix_seed_metadata_id'), table_name='seed_metadata')
    op.drop_table('seed_metadata')
    op.drop_index('ix_pre_onboarding_expires_at', table_name='pre_onboarding_customers')
    op.drop_index(op.f('ix_pre_onboarding_customers_phone_number'), table_name='pre_onboarding_customers')
    op.drop_index(op.f('ix_pre_onboarding_customers_otp_hash'), table_name='pre_onboarding_customers')
    op.drop_table('pre_onboarding_customers')
    op.drop_index(op.f('ix_kyc_document_types_id'), table_name='kyc_document_types')
    op.drop_table('kyc_document_types')
    op.drop_index(op.f('ix_fuel_types_master_id'), table_name='fuel_types_master')
    op.drop_table('fuel_types_master')
    op.drop_index('ix_drivers_name', table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_created_by'), table_name='drivers')
    op.drop_index('ix_drivers_active_available_created', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('ix_customers_verification_flags', table_name='customers')
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index('ix_customers_active_created', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_countries_master_id'), table_name='countries_master')
    op.drop_table('countries_master')
    op.drop_index(op.f('ix_cab_types_master_id'), table_name='cab_types_master')
    op.drop_table('cab_types_master')
    op.drop_index(op.f('ix_airports_master_region_code'), table_name='airports_master')
    op.drop_table('airports_master')
    # ### end Alembic commands ###
