"""change-table-name-to-trip-ratings

Revision ID: e812eb0dfff3
Revises: 3db86ccddd92
Create Date: 2026-03-29 00:35:13.778107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e812eb0dfff3'
down_revision: Union[str, Sequence[str], None] = '3db86ccddd92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('trip_ratings',
    # sa.Column('id', mysql.CHAR(length=36), nullable=False),
    # sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    # sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    # sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    # sa.Column('rating', sa.Float(), nullable=False),
    # sa.Column('feedback', sa.String(length=500), nullable=True),
    # sa.Column('overall_experience', sa.JSON(), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('is_flagged', sa.Boolean(), nullable=False),
    # sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('driver_id', 'trip_id', 'customer_id', name='uq_driver_trip_customer_rating')
    # )
    # op.create_index(op.f('ix_trip_ratings_id'), 'trip_ratings', ['id'], unique=True)
    # op.drop_index(op.f('ix_driver_ratings_id'), table_name='driver_ratings')
    # op.drop_index(op.f('uq_driver_trip_customer_rating'), table_name='driver_ratings')
    op.drop_table('driver_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_ratings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('trip_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('customer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('rating', mysql.FLOAT(), nullable=False),
    sa.Column('feedback', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('overall_experience', mysql.JSON(), nullable=True),
    sa.Column('is_flagged', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('driver_ratings_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('driver_ratings_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('driver_ratings_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_driver_trip_customer_rating'), 'driver_ratings', ['driver_id', 'trip_id', 'customer_id'], unique=True)
    op.create_index(op.f('ix_driver_ratings_id'), 'driver_ratings', ['id'], unique=True)
    op.drop_index(op.f('ix_trip_ratings_id'), table_name='trip_ratings')
    op.drop_table('trip_ratings')
    # ### end Alembic commands ###
