"""set default none fuel type

Revision ID: f19ebc4e6790
Revises: f1a2b3c4d5e6
Create Date: 2026-09-14 01:41:45.379836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f19ebc4e6790'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airport_cab_pricing_region_id'), table_name='airport_cab_pricing')
    op.drop_index(op.f('ix_local_cab_pricing_region_id'), table_name='local_cab_pricing')
    op.drop_index(op.f('ix_outstation_cab_pricing_state_id'), table_name='outstation_cab_pricing')
    op.drop_index(op.f('ix_permit_fee_config_cab_type_id'), table_name='permit_fee_config')
    op.drop_index(op.f('ix_permit_fee_config_state_id'), table_name='permit_fee_config')
    op.alter_column('tax_configurations', 'tax_scope',
               existing_type=mysql.VARCHAR(length=64),
               comment='Taxable charge scope, e.g. platform_fee, ride_fee.',
               existing_comment='Taxable charge scope, e.g. platform_fee.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax_configurations', 'tax_scope',
               existing_type=mysql.VARCHAR(length=64),
               comment='Taxable charge scope, e.g. platform_fee.',
               existing_comment='Taxable charge scope, e.g. platform_fee, ride_fee.',
               existing_nullable=False)
    op.create_index(op.f('ix_permit_fee_config_state_id'), 'permit_fee_config', ['state_id'], unique=False)
    op.create_index(op.f('ix_permit_fee_config_cab_type_id'), 'permit_fee_config', ['cab_type_id'], unique=False)
    op.create_index(op.f('ix_outstation_cab_pricing_state_id'), 'outstation_cab_pricing', ['state_id'], unique=False)
    op.create_index(op.f('ix_local_cab_pricing_region_id'), 'local_cab_pricing', ['region_id'], unique=False)
    op.create_index(op.f('ix_airport_cab_pricing_region_id'), 'airport_cab_pricing', ['region_id'], unique=False)
    # ### end Alembic commands ###
