"""rename tolls and parking columns

Revision ID: f357b2179361
Revises: ffd50d1ffc63
Create Date: 2026-02-15 16:05:40.848241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f357b2179361'
down_revision: Union[str, Sequence[str], None] = 'ffd50d1ffc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns after 'driver_allowance' and set default values to 0.0
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
