"""db-changes-01032026-v2

Revision ID: f70c490b8b1f
Revises: 62842d366e66
Create Date: 2026-03-01 01:42:30.181270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70c490b8b1f'
down_revision: Union[str, Sequence[str], None] = '62842d366e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('refund_id', sa.String(length=64), nullable=True))
    op.add_column('trips', sa.Column('refund_status', sa.String(length=32), nullable=True))
    op.add_column('trips', sa.Column('refund_type', sa.String(length=32), nullable=True))
    op.add_column('trips', sa.Column('refund_initiated_datetime', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'trips', ['refund_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_column('trips', 'refund_initiated_datetime')
    op.drop_column('trips', 'refund_type')
    op.drop_column('trips', 'refund_status')
    op.drop_column('trips', 'refund_id')
    # ### end Alembic commands ###
