"""drop minimum preauth cols

Revision ID: fb19df47744b
Revises: 8522de7b932c
Create Date: 2026-02-02 02:39:26.280123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb19df47744b'
down_revision: Union[str, Sequence[str], None] = '8522de7b932c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tripwise_pricing_config', 'minimum_toll_wallet')
    op.drop_column('tripwise_pricing_config', 'minimum_parking_wallet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
