# core/country_settings/in.py
COUNTRY= "India"
CODE = "IN"
LANGUAGE = "en"
CURRENCY = "INR"
CURRENCY_SYMBOL = "₹"
CURRENCY_DECIMAL_PLACES = 2
CURRENCY_FORMAT = "{:,.2f}"
CURRENCY_DECIMAL_SEPARATOR = "."
PHONE_NUMBER_FORMAT = "+91XXXXXXXXXX"
PHONE_NUMBER_REGEX = r'[6-9]\d{9}'
PHONE_NUMBER_VALIIDATION_ERROR = 'Invalid Indian phone number. Must be 10 digits and start with 6-9.'
PHONE_NUMBER_COUNTRY_CODE = "+91"
FLAG="🇮🇳"
TIMEZONE = "Asia/Kolkata"
