# core/country_settings/us.py
COUNTRY= "United States"
CODE = "US"
LANGUAGE = "en"
CURRENCY = "USD"
CURRENCY_SYMBOL = "$"
CURRENCY_DECIMAL_PLACES = 2
CURRENCY_FORMAT = "{:,.2f}"
CURRENCY_DECIMAL_SEPARATOR = "."
PHONE_NUMBER_FORMAT = "+1XXXXXXXXXX"
PHONE_NUMBER_REGEX = r'[2-9]\d{9}'
PHONE_NUMBER_VALIIDATION_ERROR = 'Invalid US phone number. Must be 10 digits and start with 2-9.'
PHONE_NUMBER_COUNTRY_CODE = "+1"
FLAG="🇺🇸"
TIMEZONE = "America/New_York"